# Driver de H2
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:springboot2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=

# Mostrar SQL en consola
spring.jpa.show-sql=true

# Crear esquema automáticamente
spring.jpa.hibernate.ddl-auto=create

# Consola web de H2 habilitada
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# --- ACTUATOR ---
# Expón endpoints específicos (recomendado en dev)
management.endpoints.web.exposure.include=*
# Cambia el path base si quieres
management.endpoints.web.base-path=/actuator
# (Opcional) separa el puerto del actuator
# management.server.port=8081

# Health con detalles (útil en dev; en prod suele ser 'never' o 'when_authorized')
management.endpoint.health.show-details=always

# Info (si quieres mostrar datos de la app)
spring.info.build.enabled=true
spring.info.git.enabled=true

# (recomendado) ?graceful shutdown?
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s

