spring:
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:}
    username: ${SPRING_DATASOURCE_USERNAME:}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    url: ${SPRING_DATASOURCE_URL:}
  jpa:
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
server:
  port: 8070
